a = input ("Введите дату: ")
b = input ("Введите задачу: ")
a2 = input ("Введите дату: ")
b2 = input ("Введите задачу: ")
a3 = input ("Введите дату: ")
b3 = input ("Введите задачу: ")
print (str(a), str(b))
print (str(a2), str(b2))
print (str(a3), str(b3))